"""
file_saver.py — The File Saver Agent.

WHAT IT DOES:
  Takes the final markdown report and saves it to the `reports/` directory.
  The filename is derived from the research question (sanitized to be safe).

SECURITY NOTE:
  We use regex to strip all non-alphanumeric characters from the question
  before using it as a filename. This prevents path traversal attacks like:
    question = "../../etc/passwd"
  The sanitized filename would be "etc_passwd_report.md" — harmless.

ALSO:
  Prepends an AI disclaimer banner to every saved report so readers
  know it was AI-generated and should verify critical facts.
"""

import re
import uuid
from pathlib import Path

from app.agents.state import ChatState


# ── AI Disclaimer Banner ──────────────────────────────────────────────────────

_DISCLAIMER = (
    "> ⚠️ **AI Disclaimer & Warning:**\n"
    "> This report was autonomously generated by an AI research assistant. "
    "AI models can make mistakes, hallucinate details, or generate inaccurate, "
    "outdated, or unnecessary content. Please independently verify critical facts, "
    "citations, and technical claims before relying on this document.\n\n---\n\n"
)


# ── Agent function ────────────────────────────────────────────────────────────

def file_saver(state: ChatState) -> dict:
    """
    LangGraph node: File Saver Agent.

    Reads:  state["final_report"]
            state["question"]
    Writes: state["saved_file_path"]
    """
    report_content = state["final_report"]
    question = state["question"]

    # ── Normalize the question to a string ────────────────────────────────────
    # (It should always be a string, but be defensive just in case)
    if isinstance(question, dict):
        question = question.get("question") or question.get("text") or str(question)
    question = str(question)

    # ── Normalize the report to a string ─────────────────────────────────────
    if isinstance(report_content, list):
        report_content = "\n\n".join(
            str(item.get("text", item) if isinstance(item, dict) else item)
            for item in report_content
        )
    elif isinstance(report_content, dict):
        report_content = report_content.get("text", str(report_content))
    else:
        report_content = str(report_content)

    # ── Prepend the AI disclaimer ─────────────────────────────────────────────
    final_content = _DISCLAIMER + report_content

    # ── Create a safe filename from the question ──────────────────────────────
    # Step 1: Replace any non-alphanumeric character with underscore
    safe_title = re.sub(r"[^a-zA-Z0-9]+", "_", question.strip().lower())
    # Step 2: Collapse multiple underscores into one
    safe_title = re.sub(r"_+", "_", safe_title).strip("_")
    # Step 3: Limit length to 50 characters
    safe_title = safe_title[:50].rstrip("_")
    # Step 4: Fall back to a generic name if the question was all special chars
    if not safe_title:
        safe_title = "research_report"

    # ── Save the report ───────────────────────────────────────────────────────
    output_dir = Path("reports")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"{safe_title}_{uuid.uuid4().hex[:8]}_report.md"
    output_path.write_text(final_content, encoding="utf-8")

    print(f"✅ Report saved to: {output_path}")

    return {"saved_file_path": str(output_path)}
